# Need to add test job

js_lint:
  before_script:
    - npm config set loglevel warn && npm set progress=false
    - npm install -g standard --loglevel=warn
    - cd ./wp-content/themes/barrel-base
  image: node:6
  stage: test
  script: standard
